/*
Unfold Toolbar v0.3.2
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => UnfoldToolbarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  rowsPhonePortrait: 4,
  rowsPhoneLandscape: 2,
  rowsTablet: 4,
  startFolded: true,
  animate: false
};
var ROW_LAYOUTS = {
  rowsPhonePortrait: { choices: [2, 3, 4, 5, 6], cssKey: "phone-portrait" },
  rowsPhoneLandscape: { choices: [1, 2, 3], cssKey: "phone-landscape" },
  rowsTablet: { choices: [2, 3, 4, 5, 6, 7, 8], cssKey: "tablet" }
};
var UNFOLDED_CLASS = "ut-unfolded";
var TOOLBAR_OPEN_CLASS = "mod-toolbar-open";
var STATE_KEY = "unfold-toolbar-unfolded";
var ICON_ID = "unfold-toolbar-chevron";
var ICON_SVG = '<svg x="0" y="0" width="100" height="100" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="m6 15 6-6 6 6"/></svg>';
var BUTTONS_PROP = "--ut-buttons";
var COLUMNS_PROP = "--ut-columns";
var MASK_TOP_PROP = "--ut-mask-top";
var MASK_HEIGHT_PROP = "--ut-mask-height";
var FADE_TOP_PROP = "--ut-fade-top";
var FADE_BOTTOM_PROP = "--ut-fade-bottom";
var FADE_ROWS = 0.8;
var SHIFT_PROP = "--ut-frame-shift";
var MORE_ABOVE_CLASS = "ut-more-above";
var MORE_BELOW_CLASS = "ut-more-below";
var FITTED_CLASS = "ut-fitted";
var UNFOLDING_CLASS = "ut-unfolding";
var FOLDING_CLASS = "ut-folding";
var UNFOLD_MS = 150;
var FOLD_MS = 110;
var FRAME_SELECTOR = ".mobile-toolbar-options-list-container";
var LIST_SELECTOR = ".mobile-toolbar-options-list";
var SWIPE_MIN_DISTANCE = 30;
var SWIPE_RATIO = 1.5;
var SWIPE_MAX_MS = 700;
var CSS_PROPS = [
  ...Object.values(ROW_LAYOUTS).flatMap(({ cssKey }) => [`--ut-list-${cssKey}`, `--ut-toolbar-${cssKey}`]),
  BUTTONS_PROP,
  COLUMNS_PROP,
  MASK_TOP_PROP,
  MASK_HEIGHT_PROP,
  FADE_TOP_PROP,
  FADE_BOTTOM_PROP,
  SHIFT_PROP
];
var UnfoldToolbarPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.scrollFrame = null;
    this.motionTimer = null;
    /** The fade's next update while the rows scroll, at most one per frame. */
    this.hintFrame = null;
    /** Full length of the fade in pixels; set from the theme's row height in applyHeights(). */
    this.fadeLength = 44 * FADE_ROWS;
    this.swipe = null;
    /** Runs once the screen has stopped resizing (a rotation fires several resize events). */
    this.relayoutAfterResize = (0, import_obsidian.debounce)(() => this.relayout(), 300, true);
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new UnfoldToolbarSettingTab(this.app, this));
    if (!import_obsidian.Platform.isMobile)
      return;
    (0, import_obsidian.addIcon)(ICON_ID, ICON_SVG);
    this.addCommand({
      id: "toggle",
      name: "Fold or unfold",
      icon: ICON_ID,
      editorCallback: (editor) => this.toggle(editor)
    });
    this.applyHeights();
    this.registerEvent(this.app.workspace.on("css-change", () => this.applyHeights()));
    this.registerDomEvent(window, "resize", () => {
      if (this.isUnfolded())
        this.relayoutAfterResize();
    });
    this.registerDomEvent(document, "beforeinput", (evt) => this.onBeforeInput(evt), { capture: true, passive: true });
    this.registerDomEvent(document, "scroll", (evt) => this.onFrameScroll(evt), { capture: true, passive: true });
    this.registerDomEvent(document, "touchstart", (evt) => this.onTouchStart(evt), { capture: true, passive: true });
    this.registerDomEvent(document, "touchend", (evt) => this.onTouchEnd(evt), { capture: true, passive: false });
    this.registerDomEvent(document, "touchcancel", () => this.swipe = null, { capture: true, passive: true });
    if (!this.settings.startFolded && this.app.loadLocalStorage(STATE_KEY) === true) {
      document.body.addClass(UNFOLDED_CLASS);
    }
    let wasOpen = document.body.hasClass(TOOLBAR_OPEN_CLASS);
    const observer = new MutationObserver(() => {
      const isOpen = document.body.hasClass(TOOLBAR_OPEN_CLASS);
      if (isOpen && !wasOpen) {
        this.countButtons();
        if (this.isUnfolded())
          this.layoutUnfolded();
      }
      if (wasOpen && !isOpen && this.settings.startFolded)
        this.setUnfolded(false);
      wasOpen = isOpen;
    });
    observer.observe(document.body, { attributes: true, attributeFilter: ["class"] });
    this.register(() => observer.disconnect());
  }
  onunload() {
    this.relayoutAfterResize.cancel();
    if (this.scrollFrame !== null)
      window.cancelAnimationFrame(this.scrollFrame);
    this.scrollFrame = null;
    if (this.hintFrame !== null)
      window.cancelAnimationFrame(this.hintFrame);
    this.hintFrame = null;
    if (this.motionTimer !== null)
      window.clearTimeout(this.motionTimer);
    this.motionTimer = null;
    document.body.removeClass(UNFOLDED_CLASS, UNFOLDING_CLASS, FOLDING_CLASS, MORE_ABOVE_CLASS, MORE_BELOW_CLASS, FITTED_CLASS);
    document.body.setCssProps(Object.fromEntries(CSS_PROPS.map((prop) => [prop, ""])));
    (0, import_obsidian.removeIcon)(ICON_ID);
  }
  async loadSettings() {
    const data = await this.loadData();
    const merged = { ...DEFAULT_SETTINGS, ...data };
    const rows = (key) => {
      const value = Number(merged[key]);
      return ROW_LAYOUTS[key].choices.includes(value) ? value : DEFAULT_SETTINGS[key];
    };
    const flag = (key) => {
      const value = merged[key];
      return typeof value === "boolean" ? value : DEFAULT_SETTINGS[key];
    };
    this.settings = {
      rowsPhonePortrait: rows("rowsPhonePortrait"),
      rowsPhoneLandscape: rows("rowsPhoneLandscape"),
      rowsTablet: rows("rowsTablet"),
      startFolded: flag("startFolded"),
      animate: flag("animate")
    };
  }
  /** Settings changed on another device and arrived through sync. */
  async onExternalSettingsChange() {
    await this.loadSettings();
    if (import_obsidian.Platform.isMobile)
      this.applyHeights();
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (import_obsidian.Platform.isMobile)
      this.applyHeights();
  }
  /** Called when "Start folded" changes: keep or drop this device's remembered state. */
  onStartFoldedChanged() {
    if (!import_obsidian.Platform.isMobile)
      return;
    this.app.saveLocalStorage(STATE_KEY, this.settings.startFolded ? null : this.isUnfolded());
  }
  /** Unfolded, and not on the way to folding. */
  isUnfolded() {
    return document.body.hasClass(UNFOLDED_CLASS) && !document.body.hasClass(FOLDING_CLASS);
  }
  toggle(editor) {
    this.setUnfolded(!this.isUnfolded(), true);
    if (!editor)
      return;
    if (this.scrollFrame !== null)
      window.cancelAnimationFrame(this.scrollFrame);
    this.scrollFrame = window.requestAnimationFrame(() => {
      this.scrollFrame = null;
      const cursor = editor.getCursor("head");
      editor.scrollIntoView({ from: cursor, to: cursor });
    });
  }
  /**
   * Rotation workaround for iOS: lays the toolbar out folded, then unfolded again, so no
   * width measured for the previous orientation survives, and clears any sideways scroll
   * the toolbar picked up while the screen was turning.
   */
  relayout() {
    if (!this.isUnfolded())
      return;
    document.body.removeClass(UNFOLDED_CLASS);
    document.body.getBoundingClientRect();
    document.body.addClass(UNFOLDED_CLASS);
    const frame = document.body.querySelector(".mobile-toolbar-options-list-container");
    if (frame)
      frame.scrollLeft = 0;
    this.layoutUnfolded();
  }
  /** `animate` is true for the user's own fold and unfold, so only those get the motion. */
  setUnfolded(unfolded, animate = false) {
    const motion = animate && this.settings.animate && unfolded !== this.isUnfolded() && !window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    this.stopMotion();
    if (!this.settings.startFolded)
      this.app.saveLocalStorage(STATE_KEY, unfolded);
    if (unfolded) {
      this.countButtons();
      document.body.addClass(UNFOLDED_CLASS);
      this.layoutUnfolded();
      if (motion)
        this.startMotion(UNFOLDING_CLASS, UNFOLD_MS);
    } else if (motion) {
      this.startMotion(FOLDING_CLASS, FOLD_MS, () => this.fold());
    } else {
      this.fold();
    }
  }
  fold() {
    if (this.hintFrame !== null)
      window.cancelAnimationFrame(this.hintFrame);
    this.hintFrame = null;
    document.body.removeClass(UNFOLDED_CLASS, MORE_ABOVE_CLASS, MORE_BELOW_CLASS, FITTED_CLASS);
  }
  startMotion(cls, duration, then) {
    document.body.addClass(cls);
    this.motionTimer = window.setTimeout(() => {
      this.motionTimer = null;
      document.body.removeClass(cls);
      then == null ? void 0 : then();
    }, duration);
  }
  /** Ends any motion at once; a fold that was under way is dropped, as the caller decides the state. */
  stopMotion() {
    if (this.motionTimer !== null)
      window.clearTimeout(this.motionTimer);
    this.motionTimer = null;
    document.body.removeClass(UNFOLDING_CLASS, FOLDING_CLASS);
  }
  /**
   * The unfolded toolbar gets the same width the folded one has (buttons × button width),
   * set explicitly: a content-sized width can be left stale after rotating the screen.
   */
  countButtons() {
    const list = document.body.querySelector(".mobile-toolbar-options-list");
    const count = list ? list.childElementCount : 0;
    document.body.setCssProps({ [BUTTONS_PROP]: count > 0 ? String(count) : "" });
  }
  /** Lays out the unfolded rows: whole columns only, then the fade on hidden rows. */
  layoutUnfolded() {
    this.snapColumns();
    this.updateOverflowHint();
  }
  /**
   * Narrows the unfolded toolbar to the whole columns that fit, so no empty strip is left
   * at its right end. Its left edge stays put, so no button moves: the room it frees goes to its right.
   */
  snapColumns() {
    document.body.removeClass(FITTED_CLASS);
    document.body.setCssProps({ [COLUMNS_PROP]: "", [SHIFT_PROP]: "" });
    const frame = document.body.querySelector(FRAME_SELECTOR);
    const list = frame == null ? void 0 : frame.querySelector(LIST_SELECTOR);
    const button = list == null ? void 0 : list.firstElementChild;
    if (!frame || !list || !(button instanceof HTMLElement))
      return;
    const buttonWidth = button.getBoundingClientRect().width;
    const style = getComputedStyle(list);
    const room = list.clientWidth - parseFloat(style.paddingLeft) - parseFloat(style.paddingRight);
    if (!(buttonWidth > 0) || !(room > 0))
      return;
    const columns = Math.min(list.childElementCount, Math.max(1, Math.floor((room + 0.5) / buttonWidth)));
    if (columns >= list.childElementCount)
      return;
    const left = frame.getBoundingClientRect().left;
    document.body.addClass(FITTED_CLASS);
    document.body.setCssProps({ [COLUMNS_PROP]: String(columns) });
    const shift = left - frame.getBoundingClientRect().left;
    if (Math.abs(shift) > 0.5)
      document.body.setCssProps({ [SHIFT_PROP]: `${shift}px` });
  }
  /** How far the list reaches above and below the visible rows, in pixels, from the actual layout. */
  hiddenRows() {
    const frame = document.body.querySelector(FRAME_SELECTOR);
    const list = frame == null ? void 0 : frame.querySelector(LIST_SELECTOR);
    if (!frame || !list)
      return null;
    const visibleTop = frame.getBoundingClientRect().top + frame.clientTop;
    const listRect = list.getBoundingClientRect();
    return { frame, above: visibleTop - listRect.top, below: listRect.bottom - (visibleTop + frame.clientHeight) };
  }
  /**
   * Fades the edge of the rows where more buttons are out of sight, and nothing otherwise.
   * Each fade is as long as what is hidden on its side, up to fadeLength, so it grows and
   * shrinks smoothly while the rows scroll instead of appearing at once.
   */
  updateOverflowHint() {
    const rows = this.isUnfolded() ? this.hiddenRows() : null;
    const above = rows !== null && rows.above > 1;
    const below = rows !== null && rows.below > 1;
    document.body.toggleClass(MORE_ABOVE_CLASS, above);
    document.body.toggleClass(MORE_BELOW_CLASS, below);
    const fade = (hidden) => `${Math.min(Math.max(hidden, 0), this.fadeLength)}px`;
    document.body.setCssProps(
      rows !== null && (above || below) ? {
        [MASK_TOP_PROP]: `${rows.above}px`,
        [MASK_HEIGHT_PROP]: `${rows.frame.clientHeight}px`,
        [FADE_TOP_PROP]: fade(rows.above),
        [FADE_BOTTOM_PROP]: fade(rows.below)
      } : { [MASK_TOP_PROP]: "", [MASK_HEIGHT_PROP]: "", [FADE_TOP_PROP]: "", [FADE_BOTTOM_PROP]: "" }
    );
  }
  /** Keeps the fade on the rows while they scroll: one update per frame. */
  onFrameScroll(evt) {
    if (!this.isUnfolded())
      return;
    if (!(evt.target instanceof Element) || !evt.target.matches(FRAME_SELECTOR))
      return;
    if (this.hintFrame !== null)
      return;
    this.hintFrame = window.requestAnimationFrame(() => {
      this.hintFrame = null;
      this.updateOverflowHint();
    });
  }
  /**
   * Typing in the note folds the toolbar. Toolbar commands change the note without this event,
   * so tapping them, even repeatedly, keeps it open.
   * Undo and redo from the system (shake to undo) and its text formatting don't count as typing.
   */
  onBeforeInput(evt) {
    if (!this.isUnfolded())
      return;
    if (evt.inputType.startsWith("history") || evt.inputType.startsWith("format"))
      return;
    if (!(evt.target instanceof Element) || !evt.target.closest(".cm-content"))
      return;
    this.setUnfolded(false, true);
  }
  onTouchStart(evt) {
    this.swipe = null;
    if (evt.touches.length !== 1)
      return;
    if (!(evt.target instanceof Element) || !evt.target.closest(FRAME_SELECTOR))
      return;
    const touch = evt.touches[0];
    const rows = this.isUnfolded() ? this.hiddenRows() : null;
    this.swipe = { x: touch.clientX, y: touch.clientY, time: evt.timeStamp, moreAbove: rows !== null && rows.above > 1 };
  }
  /** Swipe up unfolds. Swipe down folds, once no rows are hidden above: until then it scrolls them into view. */
  onTouchEnd(evt) {
    var _a;
    const start = this.swipe;
    this.swipe = null;
    if (!start || evt.changedTouches.length !== 1)
      return;
    const touch = evt.changedTouches[0];
    const dx = touch.clientX - start.x;
    const dy = touch.clientY - start.y;
    if (evt.timeStamp - start.time > SWIPE_MAX_MS)
      return;
    if (Math.abs(dy) < SWIPE_MIN_DISTANCE || Math.abs(dy) < SWIPE_RATIO * Math.abs(dx))
      return;
    const unfolded = this.isUnfolded();
    const wanted = dy < 0 ? !unfolded : unfolded && !start.moreAbove;
    if (!wanted)
      return;
    evt.preventDefault();
    this.toggle((_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor);
  }
  /**
   * Publishes the unfolded sizes in pixels for each kind of screen.
   * The extra rows are added on top of Obsidian's own single-row height, so the
   * bottom row stays exactly where the folded toolbar was.
   * Plain pixel values (not calc) keep --mobile-toolbar-height readable by Obsidian's own code.
   */
  applyHeights() {
    const style = getComputedStyle(document.body);
    const rowHeight = parseFloat(style.getPropertyValue("--touch-size-m")) || 44;
    const toolbarHeight = parseFloat(style.getPropertyValue("--touch-size-l")) || 52;
    const props = {};
    for (const key of Object.keys(ROW_LAYOUTS)) {
      const rows = this.settings[key];
      const { cssKey } = ROW_LAYOUTS[key];
      props[`--ut-list-${cssKey}`] = `${rows * rowHeight}px`;
      props[`--ut-toolbar-${cssKey}`] = `${toolbarHeight + (rows - 1) * rowHeight}px`;
    }
    document.body.setCssProps(props);
    this.fadeLength = rowHeight * FADE_ROWS;
    if (this.isUnfolded())
      this.layoutUnfolded();
  }
};
var TEXT = {
  startFolded: {
    name: "Start folded",
    desc: "The toolbar opens as a single row each time you start editing. Turn off to keep it the way you left it on this device."
  },
  animate: {
    name: "Animate",
    desc: "The toolbar unfolds and folds with a short motion. Skipped when your device is set to reduce motion."
  },
  rowsHeading: "Rows when unfolded",
  rowsPhonePortrait: { name: "Phone, portrait", desc: "" },
  rowsPhoneLandscape: {
    name: "Phone, landscape",
    desc: "The keyboard takes most of the screen here. Choose 1 row to keep the toolbar folded."
  },
  rowsTablet: { name: "Tablet", desc: "Used in both orientations." },
  experimentalHeading: "Experimental",
  experimentalNote: {
    name: "Features in testing",
    desc: "New features appear here first, switched off, while they are being tested. Once tested, they become standard or are removed.",
    empty: " Nothing is being tested at the moment."
  }
};
var EXPERIMENTAL_KEYS = [];
var FLAG_KEYS = ["startFolded", "animate", ...EXPERIMENTAL_KEYS];
var EXPERIMENTAL_NOTE = {
  name: TEXT.experimentalNote.name,
  desc: TEXT.experimentalNote.desc + (EXPERIMENTAL_KEYS.length === 0 ? TEXT.experimentalNote.empty : "")
};
var ROW_KEYS = ["rowsPhonePortrait", "rowsPhoneLandscape", "rowsTablet"];
var UnfoldToolbarSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  /** Obsidian 1.13+: declarative settings, indexed by the global settings search. */
  getSettingDefinitions() {
    return [
      { ...TEXT.startFolded, control: { type: "toggle", key: "startFolded" } },
      { ...TEXT.animate, control: { type: "toggle", key: "animate" } },
      {
        type: "group",
        heading: TEXT.rowsHeading,
        items: ROW_KEYS.map((key) => ({
          name: TEXT[key].name,
          desc: TEXT[key].desc || void 0,
          control: { type: "dropdown", key, options: rowOptions(key) }
        }))
      },
      {
        type: "group",
        heading: TEXT.experimentalHeading,
        items: [
          { ...EXPERIMENTAL_NOTE, searchable: false },
          ...EXPERIMENTAL_KEYS.map((key) => ({ ...TEXT[key], control: { type: "toggle", key } }))
        ]
      }
    ];
  }
  /** Dropdowns store strings; the plugin keeps numbers. */
  getControlValue(key) {
    const value = this.plugin.settings[key];
    return typeof value === "number" ? String(value) : value;
  }
  async setControlValue(key, value) {
    if (FLAG_KEYS.includes(key)) {
      this.plugin.settings[key] = value === true;
      await this.plugin.saveSettings();
      if (key === "startFolded")
        this.plugin.onStartFoldedChanged();
    } else if (ROW_KEYS.includes(key)) {
      this.plugin.settings[key] = Number(value);
      await this.plugin.saveSettings();
    }
  }
  /** Obsidian 1.8.7 to 1.12: the same settings, built by hand. */
  display() {
    const { containerEl } = this;
    containerEl.empty();
    this.addToggle(containerEl, "startFolded");
    this.addToggle(containerEl, "animate");
    new import_obsidian.Setting(containerEl).setName(TEXT.rowsHeading).setHeading();
    for (const key of ROW_KEYS) {
      const setting = new import_obsidian.Setting(containerEl).setName(TEXT[key].name);
      if (TEXT[key].desc)
        setting.setDesc(TEXT[key].desc);
      setting.addDropdown(
        (dropdown) => dropdown.addOptions(rowOptions(key)).setValue(String(this.plugin.settings[key])).onChange(async (value) => {
          await this.setControlValue(key, value);
        })
      );
    }
    new import_obsidian.Setting(containerEl).setName(TEXT.experimentalHeading).setHeading();
    new import_obsidian.Setting(containerEl).setName(EXPERIMENTAL_NOTE.name).setDesc(EXPERIMENTAL_NOTE.desc);
    for (const key of EXPERIMENTAL_KEYS)
      this.addToggle(containerEl, key);
  }
  addToggle(containerEl, key) {
    new import_obsidian.Setting(containerEl).setName(TEXT[key].name).setDesc(TEXT[key].desc).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings[key]).onChange(async (value) => {
        await this.setControlValue(key, value);
      })
    );
  }
};
function rowOptions(key) {
  const options = {};
  for (const rows of ROW_LAYOUTS[key].choices)
    options[String(rows)] = rows === 1 ? "1 row" : `${rows} rows`;
  return options;
}
