/*
Unfold Toolbar v0.2.1
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => UnfoldToolbarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  rowsPhonePortrait: 4,
  rowsPhoneLandscape: 2,
  rowsTablet: 4,
  startFolded: true
};
var ROW_LAYOUTS = {
  rowsPhonePortrait: { choices: [2, 3, 4, 5, 6], cssKey: "phone-portrait" },
  rowsPhoneLandscape: { choices: [1, 2, 3], cssKey: "phone-landscape" },
  rowsTablet: { choices: [2, 3, 4, 5, 6, 7, 8], cssKey: "tablet" }
};
var UNFOLDED_CLASS = "ut-unfolded";
var TOOLBAR_OPEN_CLASS = "mod-toolbar-open";
var STATE_KEY = "unfold-toolbar-unfolded";
var ICON_ID = "unfold-toolbar-chevron";
var ICON_SVG = '<svg x="0" y="0" width="100" height="100" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="m6 15 6-6 6 6"/></svg>';
var BUTTONS_PROP = "--ut-buttons";
var CSS_PROPS = [
  ...Object.values(ROW_LAYOUTS).flatMap(({ cssKey }) => [`--ut-list-${cssKey}`, `--ut-toolbar-${cssKey}`]),
  BUTTONS_PROP
];
var UnfoldToolbarPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.scrollFrame = null;
    /** Runs once the screen has stopped resizing (a rotation fires several resize events). */
    this.relayoutAfterResize = (0, import_obsidian.debounce)(() => this.relayout(), 300, true);
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new UnfoldToolbarSettingTab(this.app, this));
    if (!import_obsidian.Platform.isMobile)
      return;
    (0, import_obsidian.addIcon)(ICON_ID, ICON_SVG);
    this.addCommand({
      id: "toggle",
      name: "Fold or unfold",
      icon: ICON_ID,
      editorCallback: (editor) => this.toggle(editor)
    });
    this.applyHeights();
    this.registerEvent(this.app.workspace.on("css-change", () => this.applyHeights()));
    this.registerDomEvent(window, "resize", () => {
      if (document.body.hasClass(UNFOLDED_CLASS))
        this.relayoutAfterResize();
    });
    if (!this.settings.startFolded && this.app.loadLocalStorage(STATE_KEY) === true) {
      document.body.addClass(UNFOLDED_CLASS);
    }
    let wasOpen = document.body.hasClass(TOOLBAR_OPEN_CLASS);
    const observer = new MutationObserver(() => {
      const isOpen = document.body.hasClass(TOOLBAR_OPEN_CLASS);
      if (isOpen && !wasOpen)
        this.countButtons();
      if (wasOpen && !isOpen && this.settings.startFolded)
        this.setUnfolded(false);
      wasOpen = isOpen;
    });
    observer.observe(document.body, { attributes: true, attributeFilter: ["class"] });
    this.register(() => observer.disconnect());
  }
  onunload() {
    this.relayoutAfterResize.cancel();
    if (this.scrollFrame !== null)
      window.cancelAnimationFrame(this.scrollFrame);
    this.scrollFrame = null;
    document.body.removeClass(UNFOLDED_CLASS);
    document.body.setCssProps(Object.fromEntries(CSS_PROPS.map((prop) => [prop, ""])));
    (0, import_obsidian.removeIcon)(ICON_ID);
  }
  async loadSettings() {
    const data = await this.loadData();
    const merged = { ...DEFAULT_SETTINGS, ...data };
    const rows = (key) => {
      const value = Number(merged[key]);
      return ROW_LAYOUTS[key].choices.includes(value) ? value : DEFAULT_SETTINGS[key];
    };
    this.settings = {
      rowsPhonePortrait: rows("rowsPhonePortrait"),
      rowsPhoneLandscape: rows("rowsPhoneLandscape"),
      rowsTablet: rows("rowsTablet"),
      startFolded: typeof merged.startFolded === "boolean" ? merged.startFolded : DEFAULT_SETTINGS.startFolded
    };
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (import_obsidian.Platform.isMobile)
      this.applyHeights();
  }
  /** Called when "Start folded" changes: keep or drop this device's remembered state. */
  onStartFoldedChanged() {
    if (!import_obsidian.Platform.isMobile)
      return;
    this.app.saveLocalStorage(STATE_KEY, this.settings.startFolded ? null : document.body.hasClass(UNFOLDED_CLASS));
  }
  toggle(editor) {
    this.setUnfolded(!document.body.hasClass(UNFOLDED_CLASS));
    if (this.scrollFrame !== null)
      window.cancelAnimationFrame(this.scrollFrame);
    this.scrollFrame = window.requestAnimationFrame(() => {
      this.scrollFrame = null;
      const cursor = editor.getCursor("head");
      editor.scrollIntoView({ from: cursor, to: cursor });
    });
  }
  /**
   * Rotation workaround for iOS: lays the toolbar out folded, then unfolded again, so no
   * width measured for the previous orientation survives, and clears any sideways scroll
   * the toolbar picked up while the screen was turning.
   */
  relayout() {
    if (!document.body.hasClass(UNFOLDED_CLASS))
      return;
    document.body.removeClass(UNFOLDED_CLASS);
    document.body.getBoundingClientRect();
    document.body.addClass(UNFOLDED_CLASS);
    const frame = document.body.querySelector(".mobile-toolbar-options-list-container");
    if (frame)
      frame.scrollLeft = 0;
  }
  setUnfolded(unfolded) {
    if (unfolded)
      this.countButtons();
    document.body.toggleClass(UNFOLDED_CLASS, unfolded);
    if (!this.settings.startFolded)
      this.app.saveLocalStorage(STATE_KEY, unfolded);
  }
  /**
   * The unfolded toolbar gets the same width the folded one has (buttons × button width),
   * set explicitly: a content-sized width can be left stale after rotating the screen.
   */
  countButtons() {
    const list = document.body.querySelector(".mobile-toolbar-options-list");
    const count = list ? list.childElementCount : 0;
    document.body.setCssProps({ [BUTTONS_PROP]: count > 0 ? String(count) : "" });
  }
  /**
   * Publishes the unfolded sizes in pixels for each kind of screen.
   * The extra rows are added on top of Obsidian's own single-row height, so the
   * bottom row stays exactly where the folded toolbar was.
   * Plain pixel values (not calc) keep --mobile-toolbar-height readable by Obsidian's own code.
   */
  applyHeights() {
    const style = getComputedStyle(document.body);
    const rowHeight = parseFloat(style.getPropertyValue("--touch-size-m")) || 44;
    const toolbarHeight = parseFloat(style.getPropertyValue("--touch-size-l")) || 52;
    const props = {};
    for (const key of Object.keys(ROW_LAYOUTS)) {
      const rows = this.settings[key];
      const { cssKey } = ROW_LAYOUTS[key];
      props[`--ut-list-${cssKey}`] = `${rows * rowHeight}px`;
      props[`--ut-toolbar-${cssKey}`] = `${toolbarHeight + (rows - 1) * rowHeight}px`;
    }
    document.body.setCssProps(props);
  }
};
var TEXT = {
  startFolded: {
    name: "Start folded",
    desc: "The toolbar opens as a single row each time you start editing. Turn off to keep it the way you left it on this device."
  },
  rowsHeading: "Rows when unfolded",
  rowsPhonePortrait: { name: "Phone, portrait", desc: "" },
  rowsPhoneLandscape: {
    name: "Phone, landscape",
    desc: "The keyboard takes most of the screen here. Choose 1 row to keep the toolbar folded."
  },
  rowsTablet: { name: "Tablet", desc: "Used in both orientations." }
};
var ROW_KEYS = ["rowsPhonePortrait", "rowsPhoneLandscape", "rowsTablet"];
var UnfoldToolbarSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  /** Obsidian 1.13+: declarative settings, indexed by the global settings search. */
  getSettingDefinitions() {
    return [
      { ...TEXT.startFolded, control: { type: "toggle", key: "startFolded" } },
      {
        type: "group",
        heading: TEXT.rowsHeading,
        items: ROW_KEYS.map((key) => ({
          name: TEXT[key].name,
          desc: TEXT[key].desc || void 0,
          control: { type: "dropdown", key, options: rowOptions(key) }
        }))
      }
    ];
  }
  /** Dropdowns store strings; the plugin keeps numbers. */
  getControlValue(key) {
    const value = this.plugin.settings[key];
    return typeof value === "number" ? String(value) : value;
  }
  async setControlValue(key, value) {
    if (key === "startFolded") {
      this.plugin.settings.startFolded = value === true;
      await this.plugin.saveSettings();
      this.plugin.onStartFoldedChanged();
    } else if (ROW_KEYS.includes(key)) {
      this.plugin.settings[key] = Number(value);
      await this.plugin.saveSettings();
    }
  }
  /** Obsidian 1.8.7 to 1.12: the same settings, built by hand. */
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName(TEXT.startFolded.name).setDesc(TEXT.startFolded.desc).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.startFolded).onChange(async (value) => {
        await this.setControlValue("startFolded", value);
      })
    );
    new import_obsidian.Setting(containerEl).setName(TEXT.rowsHeading).setHeading();
    for (const key of ROW_KEYS) {
      const setting = new import_obsidian.Setting(containerEl).setName(TEXT[key].name);
      if (TEXT[key].desc)
        setting.setDesc(TEXT[key].desc);
      setting.addDropdown(
        (dropdown) => dropdown.addOptions(rowOptions(key)).setValue(String(this.plugin.settings[key])).onChange(async (value) => {
          await this.setControlValue(key, value);
        })
      );
    }
  }
};
function rowOptions(key) {
  const options = {};
  for (const rows of ROW_LAYOUTS[key].choices)
    options[String(rows)] = rows === 1 ? "1 row" : `${rows} rows`;
  return options;
}
